/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ceutec.proyectojuego;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
/**
 *
 * @author enzoa
 */
public class JuegoMemoria extends javax.swing.JFrame {

    /**
     * Creates new form JuegoMemoria
     */
    
    // Variables para manejar el tablero y selecciones
    private Tablero tablero; // Variable para el tablero actual
    private JButton[][] botones; // Arreglo de botones para el UI
    private int[] firstSelection = {-1, -1}; // Para guardar la primera selección del jugador

    // Labels para estadísticas
    private JLabel movimientosLabel;
    private JLabel puntosLabel;
    
    public JuegoMemoria() {
        initComponents();
        setSize(700, 700); // Example size; adjust as needed
        setLocationRelativeTo(null); // Center the JFrame on the screen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void showSubMenu(int size) {
        mainPanel.removeAll();

        JPanel subMenuPanel = new JPanel();
        subMenuPanel.setLayout(new GridLayout(2, 1));

        JButton btnContinue = new JButton("Continuar");
        JButton btnNew = new JButton("Nuevo");

        btnContinue.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                loadGame(size);
            }
        });
        btnNew.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                newGame(size);
            }
        });

        subMenuPanel.add(btnContinue);     
        subMenuPanel.add(btnNew);      

        mainPanel.add(subMenuPanel, BorderLayout.CENTER);
        mainPanel.revalidate();
        mainPanel.repaint();
    }
    
    // Método para cargar un juego existente
    private void loadGame(int size) {
        // Aquí podrías cargar el estado del juego desde un archivo o base de datos
        // Para este ejemplo, simplemente reiniciaremos el tablero
        newGame(size);
    }

    // Método para iniciar un nuevo juego
    private void newGame(int size) {
        switch (size) {
            case 4:
                tablero = new Tablero4x4();
                break;
            case 6:
                tablero = new Tablero6x6();
                break;
            case 8:
                tablero = new Tablero8x8();
                break;
            default:
                throw new IllegalArgumentException("Tamaño de tablero no soportado");
        }
        displayBoard();
    }
    
    private void displayBoard() {
        mainPanel.removeAll();
        int size = tablero.getTamano();
        mainPanel.setLayout(new GridLayout(size + 1, size));

        
        movimientosLabel = new JLabel("Movimientos: 0");
        puntosLabel = new JLabel("Puntos: 0");
        // Botón para salir del juego
        JButton salirButton = new JButton("Salir");
        salirButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Código para salir del juego
                JOptionPane.showMessageDialog(JuegoMemoria.this, "Saliendo del juego...");
                System.exit(0);
            }
        });


        // Botón para guardar juego (a implementar)
        JButton guardarButton = new JButton("Guardar");
        guardarButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Código para guardar el juego
                JOptionPane.showMessageDialog(JuegoMemoria.this, "Guardando el juego... (A implementar)");
            }
        });
        
        //guardar posiciones del statsPanel
        mainPanel.add(movimientosLabel);
        mainPanel.add(puntosLabel);
        mainPanel.add(guardarButton);
        mainPanel.add(salirButton);
        
        if(size == 6){
            mainPanel.add(new JLabel());
            mainPanel.add(new JLabel());
        }
        if(size == 8){
            mainPanel.add(new JLabel());
            mainPanel.add(new JLabel());
            mainPanel.add(new JLabel());
            mainPanel.add(new JLabel());
        }
        
        botones = new JButton[size][size];

        String[][] board = tablero.getTablero();
        boolean[][] guessed = tablero.getAdivinado();

        for (int i = 0; i < size; i++) {
            for (int j = 0; j < size; j++) {
                JButton button = new JButton();
                botones[i][j] = button;

                if (guessed[i][j]) {
                    button.setText(board[i][j]);
                } else {
                    button.setText("");
                }

                int x = i;
                int y = j;
                button.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        handleButtonClick(x, y);
                    }
                });

                mainPanel.add(button);
            }
        }

        mainPanel.revalidate();
        mainPanel.repaint();
    }

    private void handleButtonClick(int x, int y) {
        if (firstSelection[0] == -1) {
            // Primera selección
            firstSelection[0] = x;
            firstSelection[1] = y;
            botones[x][y].setText(tablero.getTablero()[x][y]);
        } else {
            // Segunda selección
            botones[x][y].setText(tablero.getTablero()[x][y]);

            if (tablero.verificarPar(firstSelection[0], firstSelection[1], x, y)) {
                // Si es un par correcto
                JOptionPane.showMessageDialog(this, "¡Par correcto!");
            } else {
                // Si no es un par correcto
                JOptionPane.showMessageDialog(this, "No es un par. Intenta de nuevo.");
                botones[firstSelection[0]][firstSelection[1]].setText("");
                botones[x][y].setText("");
            }

            // Restablecer selección
            firstSelection[0] = -1;
            firstSelection[1] = -1;
        }

        // Actualizar estadísticas de movimientos y puntos
        actualizarEstadisticas();

        // Verificar si el juego se ha ganado
        if (juegoGanado()) {
            JOptionPane.showMessageDialog(this, "¡Felicidades! Has ganado el juego.");
            System.exit(0);
        }
    }

    private void actualizarEstadisticas() {
        // Actualizar etiquetas de movimientos y puntos
        movimientosLabel.setText("Movimientos: " + tablero.getMovimientos());
        puntosLabel.setText("Puntos: " + tablero.getPuntos());
    }

    private boolean juegoGanado() {
        boolean[][] guessed = tablero.getAdivinado();
        for (int i = 0; i < guessed.length; i++) {
            for (int j = 0; j < guessed[i].length; j++) {
                if (!guessed[i][j]) {
                    return false;
                }
            }
        }
        return true;
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        radioButton4x4 = new javax.swing.JRadioButton();
        radioButton6x6 = new javax.swing.JRadioButton();
        radioButton8x8 = new javax.swing.JRadioButton();
        salirBoton = new javax.swing.JButton();
        aceptarBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout());

        mainPanel.setOpaque(false);
        mainPanel.setLayout(new java.awt.GridLayout(6, 1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Juego de Memoria");
        mainPanel.add(jLabel1);

        buttonGroup1.add(radioButton4x4);
        radioButton4x4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radioButton4x4.setText("Tablero 4x4");
        radioButton4x4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButton4x4ActionPerformed(evt);
            }
        });
        mainPanel.add(radioButton4x4);

        buttonGroup1.add(radioButton6x6);
        radioButton6x6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radioButton6x6.setText("Tablero 6x6");
        radioButton6x6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButton6x6ActionPerformed(evt);
            }
        });
        mainPanel.add(radioButton6x6);

        buttonGroup1.add(radioButton8x8);
        radioButton8x8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radioButton8x8.setText("Tablero 8x8");
        radioButton8x8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButton8x8ActionPerformed(evt);
            }
        });
        mainPanel.add(radioButton8x8);

        salirBoton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        salirBoton.setText("Salir");
        salirBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirBotonActionPerformed(evt);
            }
        });
        mainPanel.add(salirBoton);

        aceptarBoton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        aceptarBoton.setText("Aceptar");
        aceptarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarBotonActionPerformed(evt);
            }
        });
        mainPanel.add(aceptarBoton);

        getContentPane().add(mainPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioButton6x6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButton6x6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButton6x6ActionPerformed

    private void aceptarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarBotonActionPerformed
        // TODO add your handling code here:
        if (radioButton4x4.isSelected()) {
            showSubMenu(4); 
        } else if (radioButton6x6.isSelected()) {
            showSubMenu(6);
        } else if (radioButton8x8.isSelected()) {
            showSubMenu(8);
        }
    }//GEN-LAST:event_aceptarBotonActionPerformed

    private void salirBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirBotonActionPerformed
        // TODO add your handling code here:
        // Cierra la aplicación
        System.exit(0);
    }//GEN-LAST:event_salirBotonActionPerformed

    private void radioButton8x8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButton8x8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButton8x8ActionPerformed

    private void radioButton4x4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButton4x4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButton4x4ActionPerformed


    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JuegoMemoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JuegoMemoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JuegoMemoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JuegoMemoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new JuegoMemoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarBoton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JRadioButton radioButton4x4;
    private javax.swing.JRadioButton radioButton6x6;
    private javax.swing.JRadioButton radioButton8x8;
    private javax.swing.JButton salirBoton;
    // End of variables declaration//GEN-END:variables
}
